### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by Abhilash437** [gdsc-jssstu/student-chat-webapp#1]
# Current Issue:

The website is not responsive across different devices.

# What you need to do?

Make the website responsive to make it operational across different devices.

# Resources:

[Bootstrap](https://getbootstrap.com)

[W3Schools](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)

**Comment by rubensflinco** [comment]
I'm going to work on it now, I'll comment here my pull request number!

**Comment by rubensflinco** [comment]
https://github.com/gdsc-jssstu/student-chat-webapp/pull/6
