### ISSUE TITLE
Correct the UI glitches

### ISSUE THREAD

**Issue by Abhilash437** [gdsc-jssstu/student-chat-webapp#3]
# Current issue:

The UI has some glitches related to front-end, for example, the chat window overflows outside the container if there are a lot of chats and same thing with the users window.

# What do you need to do?

Use CSS to correct the issue.

# Resources:

[W3 schools - UI](https://www.w3schools.com/css/css3_user_interface.asp)

[W3 schools - Box sizing](https://www.w3schools.com/css/css3_box-sizing.asp)

[W3 schools - Overflow](https://www.w3schools.com/css/css_overflow.asp)

**Comment by Abhilash437** [comment]
Yes sure! Go ahead.

**Comment by Ommanimesh2** [comment]
@Abhilash437 I've opened a pr regarding the same . Do check it out.
