### ISSUE TITLE
The user list end point can be reached without authorisation

### ISSUE THREAD

**Issue by Abhilash437** [gdsc-jssstu/student-chat-webapp#4]
# Current issue:

The user list end point can be reached without registering or logging in.

# What you need to do?

Make some changes to the user route and make it so that only after logging in you should be able to enter the user route.

# Resources:

[Socket.io](https://socket.io/docs/v4/client-socket-instance/)

[MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP)

**Comment by avinash84319** [comment]
@Abhilash437 I have made a pull request Added authentication to users route #8 solving this issue please check it out
